In [1]:
import csv

In [2]:
import os

In [3]:
import pandas as pd

In [4]:
#prison = "../Resources/prison_custody_by_state.csv"

In [5]:
crime= "../Resources/crime_and_incarceration_by_state.csv"

In [6]:
#ucr = "Resources/ucr_by_state.csv"

In [7]:
#prison_df = pd.read_csv(prison)

In [8]:
#prison_by_state= prison_df.groupby(['jurisdiction'])

In [9]:
#prison_by_state.head()

In [11]:
crime_df=pd.read_csv(crime)
crime_df

,jurisdiction,includes_jails,year,prisoner_count,crime_reporting_change,crimes_estimated,state_population,violent_crime_total,murder_manslaughter,rape_legacy,rape_revised,robbery,agg_assault,property_crime_total,burglary,larceny,vehicle_theft
0,FEDERAL,False,2001,149852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,False,2001,24741,False,False,4468912.0,19582.0,379.0,1369.0,NaN,5584.0,12250.0,173253.0,40642.0,119992.0,12619.0
2,ALASKA,True,2001,4570,False,False,633630.0,3735.0,39.0,501.0,NaN,514.0,2681.0,23160.0,3847.0,16695.0,2618.0
3,ARIZONA,False,2001,27710,False,False,5306966.0,28675.0,400.0,1518.0,NaN,8868.0,17889.0,293874.0,54821.0,186850.0,52203.0
4,ARKANSAS,False,2001,11489,False,False,2694698.0,12190.0,148.0,892.0,NaN,2181.0,8969.0,99106.0,22196.0,69590.0,7320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,VIRGINIA,False,2016,29882,False,False,8414380.0,18495.0,482.0,NaN,2830.0,4826.0,10357.0,157292.0,20159.0,127285.0,9848.0
812,WASHINGTON,False,2016,17228,False,False,7280934.0,22101.0,195.0,NaN,3133.0,5649.0,13124.0,254994.0,49249.0,173423.0,32322.0
813,WEST VIRGINIA,False,2016,5899,False,False,1828637.0,6633.0,85.0,NaN,684.0,720.0,5144.0,37282.0,9127.0,25657.0,2498.0
814,WISCONSIN,False,2016,23163,False,False,5772917.0,17716.0,232.0,NaN,2005.0,4707.0,10772.0,111911.0,19498.0,82455.0,9958.0
815,WYOMING,False,2016,2352,False,False,584910.0,1431.0,20.0,NaN,206.0,59.0,1146.0,11460.0,1771.0,8889.0,800.0

In [ ]:
ucr_df=pd.read_csv(ucr)

In [ ]:
headers=prison_df.iloc[0]

In [ ]:
headers.head(20)

In [ ]:
prison1_df=pd.DataFrame(columns = headers)

In [ ]:
#prison1_df.head()